import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FormRegister extends javax.swing.JFrame {
    int xx, xy;
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;

    public FormRegister() {
        initComponents();
    }
    
    void Bersih(){
        jTextFieldUsername.setText("Username");
        jTextFieldPass.setText("Password");
    }
    
    private boolean registerUser(String username, String password){
        boolean isSuccess = false;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login_apotek", "root", "");
            String sql = "INSERT INTO user (username, password) VALUES (?, ?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, password);
            int rowsInserted = pst.executeUpdate();
            isSuccess = (rowsInserted > 0);
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
        return isSuccess;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonRegistrasi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jTextFieldPass = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 500));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/padlock.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 40, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 50)); // NOI18N
        jLabel2.setText("REGISTER");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 40, -1));

        jButtonRegistrasi.setBackground(new java.awt.Color(147, 152, 138));
        jButtonRegistrasi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonRegistrasi.setText("Registrasi");
        jButtonRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrasiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 128, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logoApotek.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1024, 1024));
        jLabel1.setMinimumSize(new java.awt.Dimension(1024, 1024));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jLabelLogin.setText("Sudah punya akun? Masuk disini!");
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cross.png"))); // NOI18N
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, -1));

        jTextFieldPass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPass.setText("Password");
        jTextFieldPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPassFocusLost(evt);
            }
        });
        jPanel1.add(jTextFieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 300, 40));

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsername.setText("Username");
        jTextFieldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsernameFocusLost(evt);
            }
        });
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jTextFieldPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPassFocusGained
        // TODO add your handling code here:
        String ps = jTextFieldPass.getText();
        if(ps.equals("Password")){
            jTextFieldPass.setText("");
        }
    }//GEN-LAST:event_jTextFieldPassFocusGained

    private void jTextFieldPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPassFocusLost
        // TODO add your handling code here:
        String ps = jTextFieldPass.getText();
        if(ps.equals("") || ps.equals("Password")){
            jTextFieldPass.setText("Password");
        }
    }//GEN-LAST:event_jTextFieldPassFocusLost

    private void jTextFieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsernameFocusGained
        // TODO add your handling code here:
        String user = jTextFieldUsername.getText();
        if(user.equals("Username")){
            jTextFieldUsername.setText("");
        }
    }//GEN-LAST:event_jTextFieldUsernameFocusGained

    private void jTextFieldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsernameFocusLost
        // TODO add your handling code here:
        String user = jTextFieldUsername.getText();
        if(user.equals("") || user.equals("Username")){
            jTextFieldUsername.setText("Username");
        }
    }//GEN-LAST:event_jTextFieldUsernameFocusLost

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        // TODO add your handling code here:
        FormLogin fl = new FormLogin();
        fl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void jButtonRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrasiActionPerformed
        String username = jTextFieldUsername.getText();
        String password = jTextFieldPass.getText();
        
        if(registerUser(username, password)){
            JOptionPane.showMessageDialog(null, "Registrasi Berhasil!");
            //buka form login
            FormLogin formlogin = new FormLogin();
            formlogin.setVisible(true);
            this.dispose(); //tutup form registrasi
        }else{
            JOptionPane.showMessageDialog(null, "Registrasi Gagal, Coba Lagi!");
        }
    }//GEN-LAST:event_jButtonRegistrasiActionPerformed

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
